name: Database Setup Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      sql_server:
        required: true
      sql_user:
        required: true
      sql_password:
        required: true

jobs:
  setup-database:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      SQL_SERVER: ${{ secrets.sql_server }}
      SQL_USER: ${{ secrets.sql_user }}
      SQL_PASSWORD: ${{ secrets.sql_password }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

      - name: Execute database setup
        run: |
          echo "Starting database setup for ${{ inputs.environment }} environment"
          
          {
            sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -i sql-scripts/setup.sql -l 60
          } || {
            echo "Database setup failed for ${{ inputs.environment }} environment"
            exit 1
          }

          echo "Database setup completed successfully for ${{ inputs.environment }} environment"

      - name: Verify database deployment
        run: |
          echo "Verifying database deployment for ${{ inputs.environment }} environment"
          
          {
            sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -Q "SELECT * FROM AutoDBOngeziwe.dbo.user" -l 60
          } || {
            echo "Database verification failed for ${{ inputs.environment }} environment"
            exit 1
          }

          echo "Database verification successful for ${{ inputs.environment }} environment"
